### ISSUE TITLE
URL context "/lakekeeper" not working

### ISSUE THREAD

**Issue by lefebsy** [lakekeeper/lakekeeper#1120]
**Describe the bug**
In kubernetes using helm chart with nginx ingress, the ingress path /whatever is not handled by lakekeeper. Same result with LAKEKEEPER__UI__LAKEKEEPER_URL with "http://exemple.com/whatever"

**To Reproduce**
With v0.8.4 or v0.8.5
1. Use helm chart
2. values to ingress path at /whatever and ingressClass at nginx

**Expected behavior**
Host/Whatever/ui in browser should expose lakekeeper service

**Screenshots**
Err 404

**System Information:**
 - Deployment Type: [kubernetes - vanilla yaml, kubernetes helm chart]
 - Lakekeeper Version: [0.8.5, 0.8.4]
 
 - Authentication Provider: [None]
 - Authorization Provider: [None]
 - OS: [Ubuntu]
 - Browser [any]

**Additional context**
Rust_log in debug do not write detailed informations about /context exposed.

**Comment by martyngigg** [comment]
I was just about to open the same bug report.

I've reproduced it in a docker-compose example available [here](https://gist.github.com/martyngigg/651f16a8b2f1d7e3946ddda8a61527cb). My observations are that the management & catalog APIs respond as expected, e.g.

<details>

<summary>Output of GET http://localhost:8080/lakekeeper/management/v1/warehouse</summary>

```sh
$ curl -v -L http://localhost:8080/lakekeeper/management/v1/warehouse
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 53302 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /lakekeeper/management/v1/warehouse HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx/1.27.4
< Date: Thu, 22 May 2025 08:22:05 GMT
< Content-Type: application/json
< Content-Length: 599
< Connection: keep-alive
< x-request-id: 0196f715-d5f2-72f3-afae-84002114ec89
< vary: accept-encoding
< 
* Connection #0 to host localhost left intact
{"warehouses":[{"id":"ac94089e-36e5-11f0-9ffb-070b622ad85e","name":"demo","project-id":"00000000-0000-0000-0000-000000000000","storage-profile":{"type":"s3","bucket":"examples","key-prefix":"initial-warehouse","assume-role-arn":null,"endpoint":"http://minio:9000/","region":"local-01","path-style-access":true,"sts-role-arn":null,"sts-enabled":true,"sts-token-validity-seconds":3600,"flavor":"s3-compat","allow-alternative-protocols":null,"remote-signing-url-style":"auto","push-s3-delete-disabled":true,"aws-kms-key-arn":null},"delete-profile":{"type":"hard"},"status":"active","protected":false}]}%                                                                                 
```
</details>

but the ui fails to load because the assets are not prefixed with the configured prefix path:

<details>
<summary>Output of GET http://localhost:8080/lakekeeper/ui/</summary>

```sh
$ curl -v -L http://localhost:8080/lakekeeper/ui/
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 53721 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /lakekeeper/ui/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx/1.27.4
< Date: Thu, 22 May 2025 08:32:06 GMT
< Content-Type: text/html
< Content-Length: 1241
< Connection: keep-alive
< 
<!doctype html>
<html lang="en">
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="anonymous">
    <link rel="preload" as="style" onload="this.rel='stylesheet'" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap">
    <link rel="preload" as="font" type="font/eot" href="/ui/assets/materialdesignicons-webfont-CSr8KVlo.eot" crossorigin="anonymous">
    <link rel="preload" as="font" type="font/woff2" href="/ui/assets/materialdesignicons-webfont-Dp5v-WZN.woff2" crossorigin="anonymous">
    <link rel="preload" as="font" type="font/woff" href="/ui/assets/materialdesignicons-webfont-PXm3-2wK.woff" crossorigin="anonymous">
    <link rel="preload" as="font" type="font/ttf" href="/ui/assets/materialdesignicons-webfont-B7mPwVP_.ttf" crossorigin="anonymous">

    <meta charset="UTF-8" />
    <link rel="icon" href="/ui/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lakekeeper</title>
    <script type="module" crossorigin src="/ui/assets/index-BZPDFE3y.js"></script>
    <link rel="stylesheet" crossorigin href="/ui/assets/index-BUTa9zy2.css">
  </head>

  <body>
    <div id="app"></div>
  </body>
</html>
* Connection #0 to host localhost left intact
```

</details>

**Comment by c-thiel** [comment]
Thanks for the Issue! I'll look into this.

**Comment by lefebsy** [comment]
Hello,

Maybe I am wrong, but after update in v0.9.0 and v0.9.1 I see no real amelioration.

The /context/ui return a 308 permanent redirect to location /ui/
And all the forward headers are allowed with nginx ingress annotations.

Any idea is welcome...

**Comment by c-thiel** [comment]
I am running it successfully under a subdomain.
Could you set the env var RUST_LOG=DEBUG and share the logs of some requests? I would like to see the x-forwarded headers that are logged for requests.

**Comment by lefebsy** [comment]
Of course :-)

The point is the **x-forwarded-prefix** value is unset from logs point of view.

Ingress coming from Helm chart with some tests annotations to verifiy if lakekeeper like it or not, nothing tested is really helping 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lakekeeper
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE
    nginx.ingress.kubernetes.io/enable-cors: "true"
    #nginx.ingress.kubernetes.io/x-forwarded-prefix: "/my-context"     # commented or not, with or without trailing slash
    #nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"   #https://github.com/kubernetes/ingress-nginx/issues/3670
    nginx.ingress.kubernetes.io/cors-allow-headers: "x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port,x-forwarded-prefix"
spec:
  rules:
  - host: my-host-redacted
    http:
      paths:
      - path: /my-context  # with or without trailing slash
        pathType: ImplementationSpecific
        backend:
          service:
            name: lakekeeper
            port:
              name: rest-port
  tls:
  - hosts:
    - my-host-redacted
  ```

logs extract showing **"x-forwarded-prefix":"not set"**
All the lines for any queries looks the same
_(no other specific lines containing info about url, uri, my host or my context)_
```
{"timestamp":"2025-06-20T12:38:04.715514Z","level":"DEBUG","message":"started processing request","target":"tower_http::trace::on_request","filename":"/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.6/src/trace/on_request.rs","line_number":80,"span":{"host":"my-host-redacted","method":"GET","request_id":"0498f7e79aa4624ed6ece1674352875d","uri":"/my-context/ui/","version":"HTTP/1.1","x-forwarded-host":"my-host-redacted","x-forwarded-port":"443","x-forwarded-prefix":"not set","x-forwarded-proto":"https","name":"request"},"spans":[{"host":"my-host-redacted","method":"GET","request_id":"0498f7e79aa4624ed6ece1674352875d","uri":"/my-context/ui/","version":"HTTP/1.1","x-forwarded-host":"my-host-redacted","x-forwarded-port":"443","x-forwarded-prefix":"not set","x-forwarded-proto":"https","name":"request"}]}
{"timestamp":"2025-06-20T12:38:04.715828Z","level":"DEBUG","message":"finished processing request","latency":"0 ms","status":404,"target":"tower_http::trace::on_response","filename":"/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.6/src/trace/on_response.rs","line_number":114,"span":{"host":"my-host-redacted","method":"GET","request_id":"0498f7e79aa4624ed6ece1674352875d","uri":"/my-context/ui/","version":"HTTP/1.1","x-forwarded-host":"my-host-redacted","x-forwarded-port":"443","x-forwarded-prefix":"not set","x-forwarded-proto":"https","name":"request"},"spans":[{"host":"my-host-redacted","method":"GET","request_id":"0498f7e79aa4624ed6ece1674352875d","uri":"/my-context/ui/","version":"HTTP/1.1","x-forwarded-host":"my-host-redacted","x-forwarded-port":"443","x-forwarded-prefix":"not set","x-forwarded-proto":"https","name":"request"}]}
```


Browser info for a query
```
Request URL
https://my-host-redacted/my-context/management/v1/info
Request Method
GET
Status Code
308 Permanent Redirect
Remote Address
10.146.xxx.xxx:8080
Referrer Policy
strict-origin-when-cross-origin
```


Browser info for the response Headers
```
access-control-allow-credentials
true
access-control-allow-headers
x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port,x-forwarded-prefix
access-control-allow-methods
PUT, GET, POST, OPTIONS, DELETE
access-control-allow-origin
*
access-control-max-age
1728000
content-length
0
date
Fri, 20 Jun 2025 17:12:22 GMT
location
/ui/
strict-transport-security
max-age=31536000; includeSubDomains
```

Browser info for the Request Headers
```
:authority
my-host-redacted
:method
GET
:path
/my-context/management/v1/info
:scheme
https
accept
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding
gzip, deflate, br, zstd
accept-language
fr,fr-FR;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
cache-control
no-cache
dnt
1
pragma
no-cache
priority
u=0, i
sec-ch-ua
"Chromium";v="136", "Microsoft Edge";v="136", "Not.A/Brand";v="99"
sec-ch-ua-mobile
?0
sec-ch-ua-platform
"Windows"
sec-fetch-dest
document
sec-fetch-mode
navigate
sec-fetch-site
none
sec-fetch-user
?1
upgrade-insecure-requests
1
user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0
```
