### ISSUE TITLE
Bug CatalogConfig Response Mismatch with OpenAPI Specification

### ISSUE THREAD

**Issue by manawasp** [lakekeeper/lakekeeper#1155]
Hello,

**Describe the bug**

Property `defaults` may be missing in CatalogConfig response object:
https://github.com/duckdb/duckdb-iceberg/issues/286#issuecomment-2945438672

_Initially I thought it was a duckdb extension issue so I asked for help there_

**Expected behavior**

`defaults: {}` from catalog response.

**Screenshots**

Able to attach Lakekeeper REST Catalog in DuckDB without any authn/authz (Just a local setup to play with the complete stack).

**System Information:**
 - Deployment Type: docker compose
 - Lakekeeper Version: `0.8.5` / `quay.io/lakekeeper/catalog:latest-main`
 - Query Engine: DuckDB 1.3 via Python 3.13
 - Authentication Provider: None
 - Authorization Provider: None

**To Reproduce**

<details>
<summary>Click to toggle contents of `Python script`</summary>

```python
conn = duckdb.connect(database=":memory:")
conn.execute("INSTALL httpfs; LOAD httpfs;")
conn.execute("INSTALL iceberg; LOAD iceberg;")


conn.execute("""
    CREATE SECRET lakekeeper_secret (
    TYPE ICEBERG,
    TOKEN 'dummy_token'
    );
    """)


conn.execute("""
  ATTACH 'demo' as lakekeeper_catalog (
      TYPE ICEBERG,
      ENDPOINT 'http://localhost:8181',
      SECRET lakekeeper_secret
  );
    """)
```
</details>

<details>
<summary>Click to toggle contents of `docker-compose.yml`</summary>

```yaml
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb -p local/demo;
        mc policy set public local/demo;
        exit 0;
      "

  postgresql:
    image: bitnami/postgresql:16.6.0
    container_name: lakekeeper-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 10s
    ports:
      - "5432:5432"

  catalog-migrate:
    image: quay.io/lakekeeper/catalog:latest-main
    depends_on:
      postgresql:
        condition: service_healthy
    command: migrate
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres

  lakekeeper:
    image: quay.io/lakekeeper/catalog:latest-main
    container_name: lakekeeper
    depends_on:
      create-bucket:
        condition: service_completed_successfully
      catalog-migrate:
        condition: service_completed_successfully
    ports:
      - "8181:8181"
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@lakekeeper-postgres:5432/postgres
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - RUST_LOG=info
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "/home/nonroot/lakekeeper", "healthcheck" ]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 3s

  catalog-bootstrap:
    image: curlimages/curl
    container_name: lakekeeper-tos
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    command:
      - -w
      - "%{http_code}"
      - "-X"
      - "POST"
      - "-v"
      - "http://lakekeeper:8181/management/v1/bootstrap"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - '{"accept-terms-of-use": true}'
      - "-o"
      - "/dev/null"

  init-datalakehouse:
    image: curlimages/curl
    container_name: lakekeeper-demo-warehouse-init
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    command:
      - -w
      - "%{http_code}"
      - "-X"
      - "POST"
      - "-v"
      - "http://lakekeeper:8181/management/v1/warehouse"
      - "-H"
      - "Content-Type: application/json"
      - "--data"
      - "@create-demo-warehouse.json"
      - "-o"
      - "/dev/null"
      - "--fail-with-body"
    volumes:
      - ./create-demo-warehouse.json:/home/curl_user/create-demo-warehouse.json


volumes:
  minio-data:
```
</details>

<details>
<summary>Click to toggle contents of `create-demo-warehouse.json`</summary>

```json
{
  "warehouse-name": "demo",
  "project-id": "00000000-0000-0000-0000-000000000000",
  "storage-profile": {
    "type": "s3",
    "bucket": "demo",
    "assume-role-arn": null,
    "endpoint": "http://minio:9000",
    "region": "local-01",
    "path-style-access": true,
    "flavor": "minio",
    "sts-enabled": true
  },
  "storage-credential": {
    "type": "s3",
    "credential-type": "access-key",
    "aws-access-key-id": "minioadmin",
    "aws-secret-access-key": "minioadmin"
  }
}
```
</details>
