### ISSUE TITLE
Unresponsive During High-Volume Data Ingestion

### ISSUE THREAD

**Issue by menne95** [lakekeeper/lakekeeper#623]
## Summary

When attempting to ingest a large volume of data (~3 million records per second), lakekeeper becomes unresponsive (it seems lakekeeper is stuck like not doing anything) while my data ingestor is waiting for lakekeeper to respond.

During these tests, the logs show repeated messages like the one below (meantime data was getting ingested)

```txt
{"timestamp":"2024-12-05T07:35:23.518967Z","level":"INFO","message":"No task found","target":"iceberg_catalog::implementations::postgres::task_queues::tabular_expiration_queue","filename":"crates/iceberg-catalog/src/implementations/postgres/task_queues/tabular_expiration_queue.rs","line_number":118,"span":{"name":"pick_new_task"},"spans":[{"name":"pick_new_task"}]}
```

however, we have seen many logs like the below one which caused the ingestor apps to slowly reduce the amount of data ingested per second (or even for newly deployed ingestor apps, to simply wait for the lakekeeper to reply)

```txt
{"timestamp":"2024-12-04T12:38:22.815238Z","level":"WARN","message":"acquired connection, but time to acquire exceeded slow threshold","aquired_after_secs":5.125707121,"slow_acquire_threshold_secs":2.0,"target":"sqlx::pool::acquire","filename":"/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.8.2/src/pool/inner.rs","line_number":308,"span":{"method":"POST","request_id":"2de3d474cf90ba29b84023183cc38540","uri":"/catalog/v1/9ef83972-b237-11ef-8ad7-a7d83451cc2d/namespaces/testing-full-load-v5/tables/my-table","version":"HTTP/1.1","name":"request"},"spans":[{"method":"POST","request_id":"2de3d474cf90ba29b84023183cc38540","uri":"/catalog/v1/9ef83972-b237-11ef-8ad7-a7d83451cc2d/namespaces/testing-full-load-v5/tables/my-table","version":"HTTP/1.1","name":"request"}]}
```

From a resource perspective, lakekeeper pod is using almost no CPU and memory. 

## Configuration

We are deploying lakekeeper using the helm chart version [0.1.3](https://github.com/lakekeeper/lakekeeper-charts/tree/lakekeeper-0.1.3) with the following custom values

```yaml
       catalog:
          replicas: 1
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          config:
            ICEBERG_REST__PG_READ_POOL_CONNECTIONS: 100
            ICEBERG_REST__PG_WRITE_POOL_CONNECTIONS: 100
            ICEBERG_REST__PG_CONNECTION_MAX_LIFETIME: 60
```

The storage used is minio (deployed a cluster using the https://min.io/docs/minio/kubernetes/upstream/index.html) and the warehouse is created as follows

```json
{
      "warehouse-name": "demo",
      "project-id": "00000000-0000-0000-0000-000000000000",
      "storage-profile": {
        "type": "s3",
        "bucket": "my-bucket",
        "key-prefix": "shared-minio",
        "assume-role-arn": null,
        "endpoint": "http://shared.storage.svc.cluster.local:9000",
        "region": "us-east-1",
        "path-style-access": true,
        "flavor": "minio",
        "sts-enabled": true
      },
      "storage-credential": {
        "type": "s3",
        "credential-type": "access-key",
        "aws-access-key-id": "my-user",
        "aws-secret-access-key": "my-pass"
      }
}
```

## Test 

Providing more context about the test we carried on where we face this unresponsive issue.

There are a bunch of pods that ingest data from Kafka to Iceberg. The issue described above got faced at around 1500 tables and just over 2 million msgs per second. The ingestor pods check if each table exists, and commit to every table (that contains any new data) every 120s.

We aim for around 3600 tables at least, in the long run even more. Msgs per second, we would like to at least go above 5 mil msg/second. I would roughly estimate that 1 msg is ~ 0.2 kb, which would mean something like 400 MB per second.

**Comment by twuebi** [comment]
Hi @menne95, the log saying no task found refers to task queues which is currently only used for cleanup of soft-deleted tables which isn't relevant to your issue.

Do you have access to DB metrics? How's the load on the postgres instance? Could you check the number of connections?

**Comment by c-thiel** [comment]
@menne95 that is really great to have those tests - its on our list quite high up as well!

In Version 0.5.0 of Lakekeeper (coming tomorrow) we significantly changed the database model of tables to a normalized model in Postgres (no big binary blob, instead smaller tables). It would be interesting to compare its performance, as Postgres needs to do way less. We are also very much looking forward to the day we don't have to write Metadata to S3 anymore.

It seems to me that the limiting factor is Postgres. Your second warning clearly states that obtaining connections took too long - either a sign of a bad Postgres configuration or too high load.

Would you mind sharing the code you used for your test? Then we could also analyze what Postgres is doing.

**Comment by c-thiel** [comment]
Quick follow-up: Did you use the Postgres provided by our chart?
I think it would be worth checking out CloudNativePGOperator for a bit more fine-grained control for higher loads.

The built-in version does not distinguish between read and write loads on Postgres.
https://github.com/lakekeeper/lakekeeper-charts/blob/6754a0cd28da307d1afa4f4eae30fddfc6aa9833/charts/lakekeeper/templates/config/secret-config-envs.yaml#L32-L33

Lakekeeper can distinguish this, but it needs a Postgres cluster for it to make a difference.

**Comment by menne95** [comment]
> @menne95 that is really great to have those tests - its on our list quite high up as well!
> 
> In Version 0.5.0 of Lakekeeper (coming tomorrow) we significantly changed the database model of tables to a normalized model in Postgres (no big binary blob, instead smaller tables). It would be interesting to compare its performance, as Postgres needs to do way less. We are also very much looking forward to the day we don't have to write Metadata to S3 anymore.
> 
> It seems to me that the limiting factor is Postgres. Your second warning clearly states that obtaining connections took too long - either a sign of a bad Postgres configuration or too high load.
> 
> Would you mind sharing the code you used for your test? Then we could also analyze what Postgres is doing.

Looking forward to the new release @c-thiel. 
Unfortunately, we can not share the code, it is a company private repo, however, it is a Golang application which reads from Kafka and write to Iceberg given a list of topics.

> Quick follow-up: Did you use the Postgres provided by our chart? I think it would be worth checking out CloudNativePGOperator for a bit more fine-grained control for higher loads.
> 
> The built-in version does not distinguish between read and write loads on Postgres. https://github.com/lakekeeper/lakekeeper-charts/blob/6754a0cd28da307d1afa4f4eae30fddfc6aa9833/charts/lakekeeper/templates/config/secret-config-envs.yaml#L32-L33
> 
> Lakekeeper can distinguish this, but it needs a Postgres cluster for it to make a difference.

I made that thanks to the `externalDatabase.*` values in the helm chart. We re-run the tests, however, the result is the same with many `acquired connection, but time to acquire exceeded slow threshold` logs.

I tried to bump the values of the LAKEKEEPER__PG_READ_POOL_CONNECTIONS and LAKEKEEPER__PG_WRITE_POOL_CONNECTIONS, however, it did not help much. can you guide me in the source code where you set those values and where they are used?

**Comment by c-thiel** [comment]
I found the problem - they are not being used since the last refactoring. Don't know how we overlooked this.
Fix is coming today and will be release tomorrow.

To increase your load in the meantime, did you try to scale up to more lakekeeper pods? It effectively leads to the same result: More Postgres connections in total.
Plus maybe a higher bandwidth if you set anti-affinity so that pods are on different nodes.

**Comment by c-thiel** [comment]
PG Pool size fix: https://github.com/lakekeeper/lakekeeper/pull/624

**Comment by menne95** [comment]
> PG Pool size fix: #624

This fix is also what we made in our cloned repo. Thanks for that

> I found the problem - they are not being used since the last refactoring. Don't know how we overlooked this. Fix is coming today and will be release tomorrow.
> 
> To increase your load in the meantime, did you try to scale up to more lakekeeper pods? It effectively leads to the same result: More Postgres connections in total. Plus maybe a higher bandwidth if you set anti-affinity so that pods are on different nodes.

Yeah we did, we have 3 replicas and the result is exactly the same. It seems that lakekeeper is not doing much after a few minutes (the memory and CPU used are basically none)

If it can help somehow, this is the postgres used with the increased pool connections

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-example
  namespace: lakekeeper
spec:
  instances: 1
  bootstrap:
    initdb:
      database: catalog
      secret:
        name: pg-custom-secret
  imageName: cloudnative-pg/postgresql:17.0
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50G
      storageClassName: oci-bv
    resizeInUseVolumes: true
---
apiVersion: v1
stringData:
  password: "random"
  username: "catalog"
kind: Secret
metadata:
  name: pg-custom-secret
  namespace: lakekeeper
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-example-rw
  namespace: lakekeeper
spec:
  cluster:
    name: pg-cluster-example
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "1000"
  template:
    spec:
      containers:
        - name: pgbouncer
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 500Mi
```

with its related custom values 

```yaml
        externalDatabase:
          host_read: pg-cluster-example-rw
          host_write: pg-cluster-example-rw
          passwordSecret: pg-custom-secret
          passwordSecretKey: password
          userSecret: pg-custom-secret
          userSecretKey: username
        catalog:
          config:
            ICEBERG_REST__PG_ENABLE_STATEMENT_LOGGING: "false"
            ICEBERG_REST__PG_READ_POOL_CONNECTIONS: "60"
            ICEBERG_REST__PG_WRITE_POOL_CONNECTIONS: "40"
```
