### ISSUE TITLE
Warehouse creation sometimes times out

### ISSUE THREAD

**Issue by twuebi** [lakekeeper/lakekeeper#926]
**Describe the bug**

From time to time, warehouse creation results in a 408 (e.g. https://github.com/lakekeeper/lakekeeper/actions/runs/14029107901/job/39273414217), I've seen it sometimes on CI and it has also been reported on our Discord. Could be related to a) azure being slow or b) failed requests being retried in-process while clients wait until they time out.

**To Reproduce**
No deterministic reproduction found yet

**Expected behavior**
no 408

**Screenshots**

**Comment by twuebi** [comment]
Based on [this test log](https://github.com/user-attachments/files/19445729/7_tests.spark_adls-1.6.1._.spark_adls-1.6.1.txt) it seems like the tests started running before lakekeeper was up, which is kinda odd since we have:

```yaml
    depends_on:
      server:
        condition: service_healthy
      trino:
        condition: service_healthy
```
