### ISSUE TITLE
[BUG - Kubernetes Auth]

### ISSUE THREAD

**Issue by george-zubrienko** [lakekeeper/lakekeeper#932]
**Describe the bug**
While Kubernetes Auth works with service account token from the auto-mounted file - which is a great use-case for something like an operator bootstrapping the catalog.
However, we have a different use case:
- Trino is deployed in cluster A
- Lakekeeper deployed in cluster B

Cluster A and B have direct connectivity via Cilium Cluster Mesh.

Trino wants to use k8s auth to access Lakekeeper API. Trino supports providing `iceberg.rest-catalog.oauth2.token` for authentication. Kubernetes [supports](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount) creating long-lived tokens for service accounts. Seems like all good - but unfortunately Lakekeeper can't validate long-lived tokens, because their claim structure is different from standard JWT:

![Image](https://github.com/user-attachments/assets/6157fa07-9b68-4c9d-a27e-2fe0e460c7d4)

They can, however, be validated: https://support.hashicorp.com/hc/en-us/articles/18712750429843-How-to-Check-the-Validity-of-a-JWT-Token-in-Kubernetes

I ran this for the token we've created successfully:

```
...
status:
  audiences:
  - https://kubernetes.default.svc
  authenticated: true
  user:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:data-catalog
    - system:authenticated
    uid: <redacted>
    username: system:serviceaccount:data-catalog:datacatalog-lakekeeper
```

Since I can validate the token using `tokenreview` resource, I assume Lakekeeper can as well :)

**To Reproduce**
1. Install Lakekeeper via Helm, Postgres backend, enabled Kubernetes Auth with `auth.k8s.enabled`
2. Create a secret to generate long-lived token:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: lakekeeper-sa-token
  annotations:
    kubernetes.io/service-account.name: lakekeeper
type: kubernetes.io/service-account-token
EOF
```
4. Copy the generated token and try to bootstrap using it:
```
token=...
curl -f -H "Content-Type: application/json" -H "Authorization: Bearer $token" my-lakekeeper:8181/management/v1/bootstrap -d '{"accept-terms-of-use": true}'
```
**Expected behavior**
Catalog is successfully bootstrapped and its API accessible with long-lived SA tokens.

**System Information:**
 - Deployment Type: Kubernetes - Helm
 - Lakekeeper Version: 0.7.4
 - Authentication Provider: K8s
 - Authorization Provider: None
