### ISSUE TITLE
Initial helm install fails to spawn openfga-migrate job

### ISSUE THREAD

**Issue by chcro** [lakekeeper/lakekeeper#966]
Kubernetes: 1.30.6
Helm Chart: 0.4.4

Deploying catalog and openfga postgres dbs with chart. Initial deployment does not spawn the openfga migrate job. After letting the helm timeout, the pods fail, I manually remove the pending db-migration job, a subsequent upgrade --install does spawn the pod and the instance comes up.

# helm upgrade --install lakekeeper -n lakekeeper lakekeeper/lakekeeper -f values.yaml

# helm values.yaml
```
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clusterDomain: "cluster.local"

additionalLabels:
  app: lakekeeper

helmWait: false

catalog:
  image:
    repository: quay.io/lakekeeper/catalog
    tag: v0.7.4
    pullPolicy: IfNotPresent
    uid: 65532
    gid: 65534

  replicas: &catalog_replicas 1

  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '2'
      memory: 2Gi

  nodeSelector:
    network: 10Gbit

  affinity: {}
  tolerations: []
  topologySpreadConstraints: []
  podSecurityContext:
    {}
  containerSecurityContext: {}
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  extraEnv: []
  extraEnvFrom: []
  config: {}
  safeToEvict: true

  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: ""

  livenessProbe:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 5

  readinessProbe:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 5

  autoscaling:
    enabled: false
    maxReplicas: 2
    metrics: []

  terminationPeriod: 60
  extraContainers: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraVolumes: []
  command: []

  dbMigrations:
    enabled: true
    resources: {}
    labels: {}
    podLabels: {}
    annotations: {}
    podAnnotations: {}
    extraInitContainers: []

  initContainers:
    checkDb:
      resources: {}

  service:
    annotations: {}
    sessionAffinity: "None"
    sessionAffinityConfig: {}
    type: ClusterIP
    externalPort: 8181
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort:
      http: ""

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    labels: {}
    path: "/"
    host: "<fqdn>"
    ingressClassName: "nginx"
    tls:
      enabled: true
      secretName: "lakekeeper-tls"

serviceAccount:
  create: true
  automount: true
  name: ""
  annotations: {}

secretBackend:
  type: "Postgres"
  postgres:
    encryptionKeySecret: "lakekeeper-postgres-encryptionkey"
    encryptionKeySecretKey: "encryptionKey"

postgresql:
  enabled: true
  nameOverride: "lakekeeper-pg"
  serviceBindings:
    enabled: true

  auth:
    username: catalog
    password: ""
    database: catalog
    existingSecret: ""
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"

  persistence:
    enabled: true
    storageClass: "longhorn-retain"
    accessModes:
      - ReadWriteOnce
    size: 5Gi

externalDatabase:
  type: postgres
  host_read: "localhost"
  host_write: "localhost"
  port: 5432
  database: catalog
  user: catalog
  userSecret: ""
  userSecretKey: "postgresql-user"
  password: ""
  passwordSecret: ""
  passwordSecretKey: "postgresql-password"

auth:
  oauth2:
    providerUri: "https://login.microsoftonline.com/<tenantid>/v2.0"
    audience: "api://<clientid>"
    additionalIssuers:
      - "https://sts.windows.net/<tenantid>/"
    ui:
      clientID: "<clientid>"
      scopes: "openid profile api://<clientid>/lakekeeper"
      resource: ""

  k8s:
    enabled: false
    createClusterRoleBinding: true

authz:
  backend: "openfga"
  openfga:
    endpoint: ""
    store: ""
    apiKey: ""
    clientId: ""
    clientSecret: ""
    tokenEndpoint: ""

internalOpenFGA: true

openfga:
  replicaCount: *catalog_replicas
  migrate:
    annotations:
      helm.sh/hook: "post-install, post-upgrade, post-rollback"
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/sync-wave: "0"

  datastore:
    engine: postgres
    migrationType: job
    uriSecret: lakekeeper-openfga-pg-svcbind-postgres

  postgresql:
    fullnameOverride: lakekeeper-openfga-pg
    enabled: true
    serviceBindings:
      enabled: true


```

**Comment by c-thiel** [comment]
Hey @chcro,
I think the problem is in your deployment.
My guess is this: Is by chance the `lakekeeper-openfga-pg-svcbind-postgres` created somehow by resources in this chart (that you added manually)? If so, this is most likely the problem. The helm openfga hook starts the migrate job, but it won't run as some secrets are missing. Then, after some time, they have been created and thus the second install works.

As you can see, we don't modify the OpenFGA helm chart much. If the issue persists, could you please try and install the OpenFGA helm chart directly and see if the issue persists?

**Comment by chcro** [comment]
All secrets were created by the helm chart. No modifications to secrets were made. The namespace was newly created to be sure.

**Comment by c-thiel** [comment]
In your values.yaml that you posted above you have:
```yaml
openfga:
  datastore:
    uriSecret: lakekeeper-openfga-pg-svcbind-postgres
```
This secret is not created by our helm chart, nor by the OpenFGA one. So it must be supplied externally somehow.
My point is that it must be created before the migration job.

In OpenFGA the migrate job runs with `helm.sh/hook-weight: "-5"
`:
https://github.com/openfga/helm-charts/blob/04cf7eeaef63fb5e3adf410fc5fdb441f83b4af7/charts/openfga/values.yaml#L349-L351

I think that whatever created this secret, did so after the hook was created.

Could you describe how you created the secret?
